#include <wimlib.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
struct meta {unsigned char hash[20];uint64_t size;};
static int resource(const struct wimlib_resource_entry*e,void*p){if(e->is_metadata){struct meta*m=p;memcpy(m->hash,e->sha1_hash,20);m->size=e->uncompressed_size;}return 0;}
static int getmeta(WIMStruct*w,struct meta*m){memset(m,0,sizeof(*m));return wimlib_iterate_lookup_table(w,0,resource,m);}
static int root(const struct wimlib_dir_entry*e,void*p){(void)e;(*(int*)p)++;return 0;}
static int roots(WIMStruct*w){int count=0;int r=wimlib_iterate_dir_tree(w,1,"/",0,root,&count);return r?-r:count;}
int main(int argc,char**argv){if(argc!=4)return 2;WIMStruct*a=NULL,*b=NULL,*c=NULL;wimlib_create_new_wim(0,&a);wimlib_create_new_wim(0,&b);wimlib_create_new_wim(0,&c);wimlib_add_empty_image(a,"Pending",NULL);printf("export-ab %d\n",wimlib_export_image(a,1,b,NULL,NULL,0));printf("export-bc %d\n",wimlib_export_image(b,1,c,NULL,NULL,0));struct meta ma,mb,mc;getmeta(a,&ma);getmeta(b,&mb);getmeta(c,&mc);printf("before-equal %d %d\n",memcmp(ma.hash,mb.hash,20)==0,memcmp(ma.hash,mc.hash,20)==0);printf("before-roots %d %d %d\n",roots(a),roots(b),roots(c));printf("write-a %d\n",wimlib_write(a,argv[1],-1,0,1));getmeta(a,&ma);getmeta(b,&mb);getmeta(c,&mc);printf("after-a-equal %d %d\n",memcmp(ma.hash,mb.hash,20)==0,memcmp(ma.hash,mc.hash,20)==0);unsigned nonzero=0;for(unsigned i=0;i<20;i++)nonzero|=ma.hash[i];printf("after-a-hashed %d\n",nonzero!=0);printf("after-a-roots %d %d %d\n",roots(a),roots(b),roots(c));printf("after-a-sizes %llu %llu %llu\n",(unsigned long long)ma.size,(unsigned long long)mb.size,(unsigned long long)mc.size);unsigned char saved[20];memcpy(saved,ma.hash,20);printf("write-b %d\n",wimlib_write(b,argv[2],-1,0,1));getmeta(a,&ma);getmeta(b,&mb);getmeta(c,&mc);printf("after-b-stable %d %d %d\n",memcmp(saved,ma.hash,20)==0,memcmp(saved,mb.hash,20)==0,memcmp(saved,mc.hash,20)==0);wimlib_free(a);wimlib_free(b);printf("write-c-source-freed %d\n",wimlib_write(c,argv[3],-1,0,1));getmeta(c,&mc);printf("after-c-stable %d\n",memcmp(saved,mc.hash,20)==0);printf("verify-c %d\n",wimlib_verify_wim(c,0));wimlib_free(c);return 0;}
