#include <wimlib.h>
#include <stdio.h>
#include <stdlib.h>
static int progress_mode;
static enum wimlib_progress_status second_progress(enum wimlib_progress_msg message,union wimlib_progress_info*info,void*context){(void)context;if(message==WIMLIB_PROGRESS_MSG_VERIFY_INTEGRITY)printf("integrity-second %llu %llu %u %u %u\n",(unsigned long long)info->integrity.total_bytes,(unsigned long long)info->integrity.completed_bytes,info->integrity.total_chunks,info->integrity.completed_chunks,info->integrity.chunk_size);return WIMLIB_PROGRESS_STATUS_CONTINUE;}
static enum wimlib_progress_status progress(enum wimlib_progress_msg message,union wimlib_progress_info*info,void*context){(void)context;if(message==WIMLIB_PROGRESS_MSG_VERIFY_INTEGRITY){printf("integrity %llu %llu %u %u %u\n",(unsigned long long)info->integrity.total_bytes,(unsigned long long)info->integrity.completed_bytes,info->integrity.total_chunks,info->integrity.completed_chunks,info->integrity.chunk_size);if(progress_mode==8)wimlib_register_progress_function((WIMStruct*)context,second_progress,context);return progress_mode==6?WIMLIB_PROGRESS_STATUS_ABORT:progress_mode==7?(enum wimlib_progress_status)2:WIMLIB_PROGRESS_STATUS_CONTINUE;}return WIMLIB_PROGRESS_STATUS_CONTINUE;}
static int entry(const struct wimlib_resource_entry*e,void*p){(void)p;printf("resource %llu %llu %llu %u %u %d %d ",(unsigned long long)e->uncompressed_size,(unsigned long long)e->compressed_size,(unsigned long long)e->offset,e->part_number,e->reference_count,e->is_metadata,e->packed);for(unsigned j=0;j<20;j++)printf("%02x",e->sha1_hash[j]);puts("");return 0;}
static void state(WIMStruct*w,const char*label){struct wimlib_wim_info i;wimlib_get_wim_info(w,&i);printf("state %s %u %u %u %u\n",label,i.image_count,i.boot_index,i.part_number,i.total_parts);printf("lookup %d\n",wimlib_iterate_lookup_table(w,0,entry,NULL));}
int main(int argc,char**argv){if(argc<6)return 2;int mode=atoi(argv[2]),flags=atoi(argv[3]),openflags=atoi(argv[4]);WIMStruct*w=NULL;int r=wimlib_open_wim(argv[1],0,&w);printf("open-dest %d\n",r);if(r)return 0;progress_mode=mode;if(mode>=5)wimlib_register_progress_function(w,progress,w);state(w,"before");printf("verify-before %d\n",wimlib_verify_wim(w,0));if(mode==0){unsigned n=argc-6;WIMStruct**sources=calloc(n,sizeof(*sources));for(unsigned i=0;i<n;i++){r=wimlib_open_wim(argv[i+6],0,&sources[i]);printf("open-source %u %d\n",i,r);if(r)break;}if(!r)r=wimlib_reference_resources(w,sources,n,flags);printf("reference %d\n",r);for(unsigned i=0;i<n;i++)if(sources[i])wimlib_free(sources[i]);free(sources);}else if(mode==1||mode>=5)printf("reference %d\n",wimlib_reference_resource_files(w,(const char*const*)(argv+6),argc-6,flags,openflags));else if(mode==2){WIMStruct*a[]={w,w};printf("reference %d\n",wimlib_reference_resources(w,a,2,flags));}else if(mode==4){WIMStruct*gift=NULL;wimlib_create_new_wim(0,&gift);printf("gift %d\n",wimlib_export_image(w,1,gift,NULL,NULL,WIMLIB_EXPORT_FLAG_GIFT));state(w,"gifted");printf("verify-gifted %d\n",wimlib_verify_wim(w,0));WIMStruct*restore=NULL;printf("open-restore %d\n",wimlib_open_wim(argv[1],0,&restore));printf("reference %d\n",wimlib_reference_resources(w,&restore,1,flags));wimlib_free(restore);wimlib_free(gift);}else{WIMStruct*a[]={NULL};printf("reference %d\n",wimlib_reference_resources(w,a,1,flags));}state(w,"after");printf("verify-after %d\n",wimlib_verify_wim(w,0));printf("write %d\n",wimlib_write(w,argv[5],-1,0,1));wimlib_free(w);return 0;}
