param([Parameter(Mandatory=$true)][string]$Volume,[Parameter(Mandatory=$true)][string]$FileId)
# Independent bounded raw NTFS attribute-list oracle; no volume writes.
$ErrorActionPreference='Stop';Add-Type -TypeDefinition '
using System;using System.IO;using System.Runtime.InteropServices;using Microsoft.Win32.SafeHandles;
public class SpilloverProbe {
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern SafeFileHandle CreateFile(string p,uint a,uint s,IntPtr sd,uint d,uint f,IntPtr t);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool DeviceIoControl(SafeFileHandle h,uint c,byte[] i,uint il,byte[] o,uint ol,out uint n,IntPtr ov);
 static SafeFileHandle Open(string volume){var h=CreateFile("\\\\.\\"+volume,0x80000000,7,IntPtr.Zero,3,0,IntPtr.Zero);if(h.IsInvalid)throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());return h;}
 public static byte[] Record(string volume,ulong reference){using(var h=Open(volume)){byte[] b=new byte[65536];uint n;if(!DeviceIoControl(h,0x90068,BitConverter.GetBytes(reference),8,b,(uint)b.Length,out n,IntPtr.Zero))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());Array.Resize(ref b,(int)n);return b;}}
 public static uint Cluster(string volume){using(var h=Open(volume)){byte[] b=new byte[512];uint n;if(!DeviceIoControl(h,0x90064,null,0,b,512,out n,IntPtr.Zero))throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error());uint c=BitConverter.ToUInt32(b,44);if(c<512||c>65536||(c&(c-1))!=0)throw new Exception("invalid cluster size");return c;}}
 public static byte[] Read(string volume,long offset,int length){using(var h=Open(volume))using(var f=new FileStream(h,FileAccess.Read)){f.Seek(offset,SeekOrigin.Begin);byte[] b=new byte[length];int n=0;while(n<length){int r=f.Read(b,n,length-n);if(r==0)throw new Exception("short raw volume read");n+=r;}return b;}}
}';
function Proof([string]$vol,[UInt64]$ref){$r=[SpilloverProbe]::Record($vol,$ref);if([BitConverter]::ToUInt64($r,0)-ne($ref-band0x0000ffffffffffff)){throw 'record reference mismatch'};$m=$r[12..($r.Length-1)];$o=[BitConverter]::ToUInt16($m,20);while([BitConverter]::ToUInt32($m,$o)-ne0x20){$l=[BitConverter]::ToUInt32($m,$o+4);if($l-lt24-or$o+$l-ge$m.Length){throw 'attribute list absent'};$o+=$l};if($m[$o+8]-ne1){throw 'expected nonresident list'};$len=[BitConverter]::ToUInt64($m,$o+48);$cluster=[SpilloverProbe]::Cluster($vol);$run=$o+[BitConverter]::ToUInt16($m,$o+32);if($len-gt16777216){throw 'list cap'};$assembled=New-Object IO.MemoryStream;$lcn=0L;$runCount=0;while($m[$run]-ne0){if(++$runCount-gt64){throw 'run count cap'};$ls=$m[$run]-band15;$os=$m[$run]-shr4;if($ls-lt1-or$ls-gt8-or$os-lt1-or$os-gt8){throw 'invalid list run'};$clusters=0L;$delta=0L;for($i=0;$i-lt$ls;$i++){$clusters=$clusters-bor([long]$m[$run+1+$i]-shl($i*8))};for($i=0;$i-lt$os;$i++){$delta=$delta-bor([long]$m[$run+1+$ls+$i]-shl($i*8))};if(($m[$run+$ls+$os]-band128)-ne0-and$os-lt8){$delta-=([long]1-shl($os*8))};$lcn+=$delta;if($lcn-lt0-or$clusters-lt1-or$clusters*$cluster-gt16777216){throw 'run bound'};$chunk=[SpilloverProbe]::Read($vol,$lcn*$cluster,[int]($clusters*$cluster));$assembled.Write($chunk,0,$chunk.Length);$run+=1+$ls+$os};$data=$assembled.ToArray();if($data.Length-lt$len){throw 'list too short'};$refs=New-Object 'Collections.Generic.HashSet[UInt64]';for($i=0;$i-lt$len;){$e=[BitConverter]::ToUInt16($data,$i+4);if($e-lt26-or$i+$e-gt$len){throw 'invalid list entry'};[void]$refs.Add([BitConverter]::ToUInt64($data,$i+16));$i+=$e};$extensions=@(foreach($x in $refs){$entry=[SpilloverProbe]::Record($vol,$x);$base=[BitConverter]::ToUInt64($entry,44);if([BitConverter]::ToUInt64($entry,0)-ne($x-band0x0000ffffffffffff)-or[BitConverter]::ToUInt16($entry,28)-ne($x-shr48)){throw 'record number or sequence mismatch'};if($x-ne$ref-and$base-ne$ref){throw 'extension base reference mismatch'};@{Reference=$x.ToString('X16');BaseReference=$base.ToString('X16');ReturnedReference=[BitConverter]::ToUInt64($entry,0).ToString('X16');Raw=[Convert]::ToBase64String($entry)}});@{Volume=$vol;BaseReference=$ref.ToString('X16');ListLogicalLength=$len;ListLcn=$lcn;ListRaw=[Convert]::ToBase64String($data[0..([int]$len-1)]);Records=$extensions;ExtensionCount=$refs.Count-1}}
Proof $Volume ([Convert]::ToUInt64($FileId,16))|ConvertTo-Json -Depth 6
